--REPORT 5--
--GETTING THE YOUNGER COHERT CHILD'S AGE DATA IN MONTHS FOR ETHIOPIA--
SELECT * INTO DBO.ETHO 
FROM Ethiopia

--CONNECTION 1--
BEGIN TRAN 
UPDATE DBO.ETHO
SET agemon=24
WHERE yc=1
--ROLLBACK
--CONNECTION 2 IS IN QUERY5.1---



--ANALYSING THE CHILD'S ETHNIC GROUP FOR CHILD SEX 1 IN INDIA --
SELECT * INTO DBO.IND
FROM India

--EXECUTION 1--
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT chethnic FROM DBO.IND
WHERE chsex=1

WAITFOR DELAY '00:00:05'

SELECT chethnic FROM DBO.IND
WHERE chsex=1
COMMIT TRAN
--EXECUTION 2 IS IN QUERY5.2---



--ANALYSING THE CHILD'S QUESTIONNAIRE ADMINISTRATED FOR ROUND IN PERU--
SELECT * INTO DBO.PER
FROM Peru

--EXECUTION 1--
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
DELETE FROM DBO.PER
WHERE inround BETWEEN 1 AND 5

WAITFOR DELAY '00:00:10'
BEGIN TRAN
SELECT * FROM DBO.PER
WHERE inround BETWEEN 1 AND 5
COMMIT TRAN
ROLLBACK
--EXECUTION 2 IS IN QUERY5.3---



--ANAYSING THE Child Well-Being Monitor IN VIETNAM--
CREATE FUNCTION CHILDWELLBEING(@childid VARCHAR(40))
RETURNS TABLE
AS
RETURN(SELECT childid,agemon,chweight,bmi FROM Vietnam WHERE childid=@childid)

SELECT childid,agemon,chweight,bmi FROM CHILDWELLBEING('VN010003')

