--Report 3--
----ANALYSING THE CHILD WELL-BEING MONITOR FOR COUNTRY ETHIOPIA--
SELECT childid, chweight, bmi, underweight, stunting, thinness, chhrel, chhealth, wi_new 
FROM Ethiopia
WHERE childid LIKE '%ET010100%' AND chweight IS NOT NULL 
ORDER BY chweight DESC


----CALCULATING THE AVERAGE BMI OF CHILDS FOR THE YOUNGER COHERT IN INDIA--
SELECT AVG(bmi) AS 'AVG_BMI',childid
FROM India
WHERE yc=1
GROUP BY childid 
ORDER BY childid 

----CALCULATING THE TOTAL BMI OF CHILDS FOR THE OLDER COHERT IN PERU--
SELECT SUM(bmi) AS 'SUM_BMI',childid
FROM Peru
WHERE yc=0 
GROUP BY childid 
ORDER BY childid DESC 

--CALCULATING THE CHILD'S ROUND OF SURVEY IN VIETNAM--

SELECT childid, round, GRADE=
CASE
WHEN round=1 THEN 'POOR CHILD'
WHEN round=2 THEN 'AVERAGE CHILD'
WHEN round=3 THEN 'GOOD CHILD'
WHEN round=4 THEN 'VERY GOOD CHILD'
WHEN round=5 THEN 'EXCELLENT CHILD'
ELSE 'NA'
END
FROM Vietnam
